name = "hugelton-docs"
compatibility_date = "2025-01-01"

[env.production]
compatibility_date = "2025-01-01"

[[env.production.route]]
pattern = "documents.hugelton.com/*"
custom_domain = true

[build]
command = "npm install && node build.js"
cwd = "."
destination = "./public"